### PR TITLE
Mask rasters by layer

### LINKED ISSUE #2: Handle Non Square Raster Resolution in Align Rasters

### LINKED ISSUE #74: Align Rasters should use Clip Raster by Mask Layer rather than Clip Raster by Extent
### Latest QNSPECT version

- [X] I am running the latest QNSPECT version

### Similar issue do not exist

- [X] I have searched existing issues to make sure a similar issue does not exist

### What is the bug or the crash?

QNSPECT users almost always are working within a defined area of interest such as a polygon watershed basin. Align Rasters currently clips by corner coordinates providing a rectangular output. If **Clip Raster by Mask Layer** could be used in Align Rasters the output would be based on the shape of the area of interest. 

### Steps to reproduce the issue

Go to Align Rasters
Add reference Raster and Rasters to Align
Add a polygon vector file as the Clipping Extent

### Versions

QGIS version
3.22.3-Białowieża

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ar-siddiqui**
close #2 close #74

This has revamped the `Align Rasters` tool. Should be thoroughly checked for behaviour.

### CODE REVIEW

**Review by DaveEslinger — CHANGES_REQUESTED** [review]
This is not functioning as expected.  I "aligned" 3 different files against the same DEM file, using the same shapefile AOI.  None of the rasters were clipped as expected.  All had mismatching cells.

I'm attaching some screenshots of the problems. I have a zipfile of the source data I used, but need a location to upload it.  It's ~29MB.

Data uploaded in MS Teams: https://dewberryportal.sharepoint.com/:u:/r/sites/NOAANSPECT/Shared%20Documents/General/Align_Test_data.zip?csf=1&web=1&e=j0RELy

It appears the tool is clipping the rasters at their original resolution, then reprojecting them.  This results in large missing areas, since there is a great variation in the pixel size of the original rasters.  Note that these are the actual raster data sources we use, so this is a real issue, not an artificial one.
In OpenNSPECT, to avoid the same issue, and to also avoid reprojecting a CONUS-coverage data set (3 of them are) to extract a small area, we chose to do the clipping twice:
1) Reproject the AOI into the source data's projection, with a very large buffer.
2) Clip the source
3) Reproject the clipped raster to the target projection at the target resolution.
4) Clip to final target AOI.

That should result in every raster having identical coverage.

image
image

**Comment by DaveEslinger** [comment]
In the zoomed in picture, note that parts of all rasters can be seen at the same time.  Green is R-factor, blue is Precip, tan is DEM, and the dark brown are CCAP.  If this worked correctly, only the topmost layer would be visible.

**Comment by ar-siddiqui** [comment]
@DaveEslinger fixed now. Please re-review and test.

**Review by DaveEslinger — APPROVED** [review]
Wow, this works both better and seemingly faster!  Very nice!

**Pull request merged**
